source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'XLForm', '~> 3.0.0'
pod 'JTCalendar', '~> 2.0'
pod 'JSONJoy-Swift', '~> 0.9.1'
pod 'SwiftHTTP', '~> 0.9.4'
pod 'Kingfisher', '= 1.5'
pod "MWPhotoBrowser"
pod 'MBProgressHUD', '~> 0.9.1'
pod 'Alamofire', '~> 1.3'